export const actionType = {
  DATA_INSERT: "DATA_INSERT",
  REGION_FILTER: "REGION_FILTER",
  AMENITIES_FILTER: "AMENITIES_FILTER",
  DATEPICKER_FILTER: "DATEPICKER_FILTER",
  ADD_CART: "ADD_CART",
  REMOVE_CART: "REMOVE_CART",
};
